#ifndef __FRAMEWORK_WSGOSVCTYPEDEF_H__
#define __FRAMEWORK_WSGOSVCTYPEDEF_H__

#include "../FWSvcTypeDef.h"

FW_NS_BEGIN


#define FW_WSGOSVC_SEND_BUF_SIZE	4096
#define FW_WSGOSVC_RECV_BUF_SIZE	4096
#define FW_WSGOSVC_SEND_CHAN_SIZE	8


FW_NS_END


#endif //!__FRAMEWORK_WSGOSVCTYPEDEF_H__